#!/bin/bash

if [[ $# -ne 1 ]];
then
    echo "Usage $0 <user>"
    echo ""
    echo "<user> must be the name of the user (not root), which will be configured for"
    echo "he will be added in sudo, install pip and emacs configured"
fi

if [[ $EUID -ne 0 ]];
then
    echo "Script must be launched with root"
    exit 1
fi

apt install -y sudo
sudo adduser $1 sudo
echo "$1	ALL=(ALL:ALL) ALL" >> /etc/sudoers

# some packages are already installed like wget or python3 but we never know

apt install -y xorg i3
apt install -y emacs xfce4-terminal
apt install -y alsa-utils pulseaudio
apt install -y make gcc python3 python3-full
apt install -y maim xclip feh fonts-font-awesome picom
apt install -y curl wget ffmpeg yt-dlp
apt install -y clang clangd
apt install -y git firefox-esr

cat <<EOF > /etc/X11/xorg.conf.d/pad.conf
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "ClickMethod" "buttonareas"
    Option "DisableWhileTyping" "on"
    Option "MiddleEmulation" "on"
    Option "NaturalScrolling" "on"
EndSection
EOF

runuser -l $1 -c "wget https://bootstrap.pypa.io/get-pip.py"
runuser -l $1 -c "python3 get-pip.py --break-system-packages"
runuser -l $1 -c "rm get-pip.py"
runuser -l $1 -c "/home/$1/.local/bin/pip3 install pyright --break-system-packages"

cat <<EOF >> /home/$1/.bashrc

export PATH="\$PATH:/home/$1/.local/bin"

alias emacs='emacs -nw'
alias sudo='sudo '

PS1="\[\033[m\][\[\033[4;95m\]\A\[\033[m\]]\[\e[1;36m\]\u\[\e[1;36m\]\[\033[m\]@\[\e[1;91m\]\h\[\033[m\]:\[\e[0m\]\[\e[1;35m\][\W]> \[\e[0m\]"
EOF

emacs --batch --eval "(package-install 'eglot )"
emacs --batch --eval "(package-install 'multiple-cursors )"
emacs --batch --eval "(package-install 'company )"
emacs --batch --eval "(package-install 'rainbow-delimiters )"

cp ./emacs_user_config /home/$1/.emacs
chown $1:$1 /home/$1/.emacs
cp ./emacs_root_config /root/.emacs

mkdir /home/$1/.backgrounds
chown $1:$1 /home/$1/.backgrounds
cp ./debian_wallpaper.png /home/$1/.backgrounds
chown $1:$1 /home/$1/.backgrounds

rm -rf /etc/i3/*
cp -r ./i3/* /etc/i3/
sed -i 's/DEBIAN_USER/$1/g' /etc/i3/config

reboot
